services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  silo:
    build:
      context: .
      dockerfile: OrleansAuction.Silo/Dockerfile
    ports:
      - "11111:11111"
      - "30000:30000"
      - "8081:8081"
      - "8080:8080"
    environment:
      - ConnectionStrings__AzureStorage=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://azurite
    depends_on:
      - azurite

  client:
    build:
      context: .
      dockerfile: OrleansAuction.Client/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__AzureStorage=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://azurite
    depends_on:
      - silo